### PR TITLE
Get current epoch number through internal contract

### PR DESCRIPTION
**Pull request by Thegaram**
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/cips/64)

### CODE REVIEW

**Comment by ChenxingLi** [comment]
Two comments:
1. Can we change the contract name to a more generic name, e.g. `Context`. So maybe we can support more functionalities here. 
2. The interface should be activated at a given `block number` or a given `epoch number`. Which one is better?

**Comment by Thegaram** [comment]
> 1. Can we change the contract name to a more generic name, e.g. `Context`. So maybe we can support more functionalities here.

Thank you for the suggestion, `Context` sounds much better, I updated it. Do you have any ideas what other information we might want to expose through this contract in the future?

> 2. The interface should be activated at a given `block number` or a given `epoch number`. Which one is better?

I have no strong preference here, let's use whatever approach we use in the next hard fork.

**Comment by Thegaram** [comment]
wip implementation: https://github.com/Thegaram/conflux-rust/tree/context-internal-cip-impl

**Comment by ChenxingLi** [comment]
> wip implementation: https://github.com/Thegaram/conflux-rust/tree/context-internal-cip-impl

@Thegaram I read the implementation. I think the logic related to activation time should not be implemented in the creation of `InternalContractMap` because
1. the block number may change while using the same instance of `InternalContractMap`;
2. the activation block number should be configured for each function, instead of each contract.

A better solution is making the *function table* include activation height. 

That's the comments for the implementation. I think this CIP is ready to merged.

**Comment by Thegaram** [comment]
> A better solution is making the function table include activation height.

I agree, this is a better approach.

The other question is the issue of initialization. The other three internal contract accounts are initialized in the genesis block. `Context` is read-only so strictly speaking it might not need an account but I think it's best to have one for consistency, and it will need to be created at the fork block.

**Comment by ChenxingLi** [comment]
Oh, I understand it. Because the new contract should act as a non-existent contract before the activation block. And calling a non-existent contract is different from calling an unknown function of the existing contract.

But I still think checking the block number in each message-call is a better solution. This can minimize the requirements for the implementations in transaction execution. In your current implementation, we must assume a contract will not be activated in the middle of an epoch.

**Review by ChenxingLi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/conflux-chain/cips/64#-:-MXf7iY4EnC9m8sH2382:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved

**Review by ChenxingLi — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/cips/64)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Thegaram)

**Pull request merged**
