### PR TITLE
CIP-31: put Create2Factory contract in genesis block

### PR DESCRIPTION
**Pull request by posaggen**
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/cips/32)

### CODE REVIEW

**Review by yangzhe1990 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/cips/32)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @boqiu, @posaggen, and @sparkmiw)

___
*[CIPs/cip-31.md, line 40 at r1](https://reviewable.io/reviews/conflux-chain/cips/32#-MJGn9f54tw4-NXdtlKJ:-MJGn9f54tw4-NXdtlKK:bvr0xwi) ([raw file](https://github.com/conflux-chain/cips/blob/139f40dc9ab094d689c81f4b56fafd19ea5212bb/CIPs/cip-31.md#L40)):*
> ```Markdown
>         address addr;
>         assembly {
>             addr := create2(0, add(code, 0x20), mload(code), salt)
> ```

It looks like that the calculation is based on sender address of "0x000...0", and the contract is actually deployed.

First of all, the contract is created, so create2 isn't necessary, because create1 does the job.

**Review by yangzhe1990 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/cips/32)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @boqiu, @posaggen, and @sparkmiw)

___
*[CIPs/cip-31.md, line 28 at r1](https://reviewable.io/reviews/conflux-chain/cips/32#-MJGpLEZ7YMjv1kz0LBZ:-MJGpLEZ7YMjv1kz0LB_:baz1mj9) ([raw file](https://github.com/conflux-chain/cips/blob/139f40dc9ab094d689c81f4b56fafd19ea5212bb/CIPs/cip-31.md#L28)):*
> ```Markdown
> ## Specification
> 
> ```

Consider adding a typical CREATE2 usage, and show where is this Create2Factory should be used.

**Review by yangzhe1990 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/cips/32)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @boqiu, @posaggen, and @sparkmiw)

___
*[CIPs/cip-31.md, line 40 at r1](https://reviewable.io/reviews/conflux-chain/cips/32#-MJGpvfUDAuH1wgiFN_z:-MJGpvfUDAuH1wgiFNa-:b6iy8rf) ([raw file](https://github.com/conflux-chain/cips/blob/139f40dc9ab094d689c81f4b56fafd19ea5212bb/CIPs/cip-31.md#L40)):*
> ```Markdown
>         address addr;
>         assembly {
>             addr := create2(0, add(code, 0x20), mload(code), salt)
> ```

why is the sender address 0 in create2 call?

**Review by posaggen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/cips/32)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @boqiu, @posaggen, @sparkmiw, and @yangzhe1990)

___
*[CIPs/cip-31.md, line 40 at r1](https://reviewable.io/reviews/conflux-chain/cips/32#-MJGpvfUDAuH1wgiFN_z:-MJGqQXrDwoCtz8uIv25:b1t7otb) ([raw file](https://github.com/conflux-chain/cips/blob/139f40dc9ab094d689c81f4b56fafd19ea5212bb/CIPs/cip-31.md#L40)):*
<details><summary><i>Previously, yangzhe1990 wrote…</i></summary><blockquote>

why is the sender address 0 in create2 call?
</blockquote></details>

The first parameter 0 is the amount of wei to send to the new contract as msg.value.

**Review by yangzhe1990 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/cips/32)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @boqiu, @posaggen, and @sparkmiw)

___
*[CIPs/cip-31.md, line 40 at r1](https://reviewable.io/reviews/conflux-chain/cips/32#-MJGn9f54tw4-NXdtlKJ:-MJGquak0jBTV9gAuzys:b862q7z) ([raw file](https://github.com/conflux-chain/cips/blob/139f40dc9ab094d689c81f4b56fafd19ea5212bb/CIPs/cip-31.md#L40)):*
<details><summary><i>Previously, yangzhe1990 wrote…</i></summary><blockquote>

It looks like that the calculation is based on sender address of "0x000...0", and the contract is actually deployed.

First of all, the contract is created, so create2 isn't necessary, because create1 does the job.
</blockquote></details>

please ignore, the first param isn't addr 0x0..0

**Review by boqiu — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/cips/32#-:-MJHb3YV8Ajcr8TfMxQL:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @posaggen and @sparkmiw)

___
*[CIPs/cip-31.md, line 19 at r1](https://reviewable.io/reviews/conflux-chain/cips/32#-MJHaDhU0wcUyFxVXDkW:-MJHaDhVCJyJNoWCh1iN:bvhsdp) ([raw file](https://github.com/conflux-chain/cips/blob/139f40dc9ab094d689c81f4b56fafd19ea5212bb/CIPs/cip-31.md#L19)):*
> ```
> private key
> ```

a fixed address and nonce?

Here, a dummy sender address is enough and need not to validate the signature in genesis block.

**Review by yangzhe1990 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/cips/32)* status: all files reviewed, 2 unresolved discussions (waiting on @posaggen and @sparkmiw)

___
*[CIPs/cip-31.md, line 28 at r1](https://reviewable.io/reviews/conflux-chain/cips/32#-MJGpLEZ7YMjv1kz0LBZ:-MJHqQ_wAyTxNgon_fYi:b-wn9fvt) ([raw file](https://github.com/conflux-chain/cips/blob/139f40dc9ab094d689c81f4b56fafd19ea5212bb/CIPs/cip-31.md#L28)):*
<details><summary><i>Previously, yangzhe1990 wrote…</i></summary><blockquote>

Consider adding a typical CREATE2 usage, and show where is this Create2Factory should be used.
</blockquote></details>

mark this comment discussing

**Review by yangzhe1990 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/cips/32)* status: all files reviewed, 3 unresolved discussions (waiting on @posaggen and @sparkmiw)

___
*[CIPs/cip-31.md, line 62 at r1](https://reviewable.io/reviews/conflux-chain/cips/32#-MJHqZkdAN9AhHXezzXm:-MJHqZkdAN9AhHXezzXn:b-gwcci6) ([raw file](https://github.com/conflux-chain/cips/blob/139f40dc9ab094d689c81f4b56fafd19ea5212bb/CIPs/cip-31.md#L62)):*
> ```Markdown
> 
> 
> This CIP is backward compatible. 
> ```

I think it "is not backwards compatible"

**Review by boqiu — APPROVED** [review]

**Review by boqiu — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/cips/32#-:-MJKKS5ICAUdi8b1Q4NA:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @posaggen and @sparkmiw)

**Review by sparkmiw — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/conflux-chain/cips/32#-:-MJKPBkJ6-6MNJKs4DXq:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @posaggen and @sparkmiw)

**Review by yangzhe1990 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/cips/32)* status: all files reviewed, 1 unresolved discussion (waiting on @posaggen and @sparkmiw)

**Review by sparkmiw — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/conflux-chain/cips/32#-:-MKEg5zR3WeoP4yEmJOG:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @posaggen and @sparkmiw)

**Review by yangzhe1990 — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/cips/32)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sparkmiw)

**Pull request merged**
