### PR TITLE
Create CIP-26: Use timestamp from pivot block as TIMESTAMP (opcode 42)

### PR DESCRIPTION
**Pull request by resodo**
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/cips/26)

### CODE REVIEW

**Comment by Thegaram** [comment]
I think this looks very reasonable. What about `NUMBER`? I think we should also treat it similarly (return pivot block height aka epoch instead of block height) as it is used by many Ethereum contracts as a kind of timestamp (e.g. MoonSwap). If it returns the block number (which I assume is the current implementation) then I'm not sure it has any use.

**Comment by ChenxingLi** [comment]
> I think we should also treat it similarly (return pivot block height aka epoch instead of block height) as it is used by many Ethereum contracts as a kind of timestamp (e.g. MoonSwap). If it returns the block number (which I assume is the current implementation) then I'm not sure it has any use.

The current NUMBER has a steady growth rate (2 blocks per second). But the block height/epoch number not. So I think we should not change it.

**Comment by Thegaram** [comment]
> The current NUMBER has a steady growth rate (2 blocks per second). But the block height/epoch number not. So I think we should not change it.

Oh so now NUMBER returns the block number in the total order, not the block height. Got it, that works too.

**Review by ChenxingLi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/conflux-chain/cips/26#-:-MHsoEkX-ByaRoNIideA:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ChenxingLi)

**Pull request merged**
