### PR TITLE
CIP: Add query and help interfaces for internal contracts

### PR DESCRIPTION
**Pull request by oo7ww**
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/cips/22)

### CODE REVIEW

**Review by boqiu — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/cips/22)* status: all files reviewed, 4 unresolved discussions (waiting on @ChenxingLi)

___
*[CIPs/cip-draft-Add_interface_for_internal_contracts.md, line 43 at r1](https://reviewable.io/reviews/conflux-chain/cips/22#-MF-TkHm8GOYAG3XE7z1:-MF42Mqr6UFTwDKO2wUK:b-66f71k) ([raw file](https://github.com/conflux-chain/cips/blob/df82d09b527b5392fed3ae0b62922cf2b18d5e51/CIPs/cip-draft-Add_interface_for_internal_contracts.md#L43)):*
<details><summary><i>Previously, oo7ww wrote…</i></summary><blockquote>

Done. Changed to snake case.
</blockquote></details>

@chenxingli generally, camel case is preferred in Solidity.
___
*[CIPs/cip-draft-Add_interface_for_internal_contracts.md, line 176 at r1](https://reviewable.io/reviews/conflux-chain/cips/22#-MF-VoEEDMwo6irQ_N82:-MF43bJs9wmNUQwfwCt6:b-f746tj) ([raw file](https://github.com/conflux-chain/cips/blob/df82d09b527b5392fed3ae0b62922cf2b18d5e51/CIPs/cip-draft-Add_interface_for_internal_contracts.md#L176)):*
<details><summary><i>Previously, oo7ww wrote…</i></summary><blockquote>

Fixed
</blockquote></details>

@chenxingli In my mind, this CIP just proposes some new functions, and should be backward compatible.

**Review by boqiu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/cips/22)* status: all files reviewed, 4 unresolved discussions (waiting on @ChenxingLi)

___
*[CIPs/cip-draft-Add_interface_for_internal_contracts.md, line 154 at r1](https://reviewable.io/reviews/conflux-chain/cips/22#-MF-VtyuDqYfSoeoXejc:-MF45Yf03jCVVf39xj0Q:b-yyos6f) ([raw file](https://github.com/conflux-chain/cips/blob/df82d09b527b5392fed3ae0b62922cf2b18d5e51/CIPs/cip-draft-Add_interface_for_internal_contracts.md#L154)):*
<details><summary><i>Previously, oo7ww wrote…</i></summary><blockquote>

Can the unlock block number array be returned ?
</blockquote></details>

If so, we could add only one function to return the locked amount according to current block number.

Moreover, is it possible to add API to unlock?

**Review by ChenxingLi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/cips/22)* status: all files reviewed, 1 unresolved discussion (waiting on @ChenxingLi)

___
*[CIPs/cip-draft-Add_interface_for_internal_contracts.md, line 43 at r1](https://reviewable.io/reviews/conflux-chain/cips/22#-MF-TkHm8GOYAG3XE7z1:-MF4KZcm6PReXN9HbhYQ:b7f86ap) ([raw file](https://github.com/conflux-chain/cips/blob/df82d09b527b5392fed3ae0b62922cf2b18d5e51/CIPs/cip-draft-Add_interface_for_internal_contracts.md#L43)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

@chenxingli generally, camel case is preferred in Solidity.
</blockquote></details>

Maybe we should discuss it later.

**Review by boqiu — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/cips/22#-:-MF8zm0V6FaFzLvqosf1:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ChenxingLi)

**Review by ChenxingLi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/cips/22)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
